name: My Workflow

on:
  push:
    branches: [main]

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Print Hello message
        run: echo "Hello"

      - name: Print Ubuntu version
        run: |
          lsb_release -a

      - name: Print commit SHA
        run: echo ${{ github.sha }}

  job2:
    runs-on: ubuntu-latest
    steps:
      - name: Print all files in the repository
        run: ls -al

      - name: Run test script
        run: sh test.sh

  job3:
    runs-on: ubuntu-latest
    env:
      FIRST_NAME: "John"
    steps:
      - name: Print First Name
        run: echo $FIRST_NAME

      - name: Print Last Name
        run: |
          LAST_NAME="Doe"
          echo $LAST_NAME

      - name: Print phone number
        run: |
          echo ${{ secrets.PHONE_NUMBER }}
